# Generated by Django 5.0.4 on 2024-05-08 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_notification_patient_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('systolic_blood_pressure', models.IntegerField(blank=True, help_text='Systolic blood pressure in mmHg', null=True)),
                ('diastolic_blood_pressure', models.IntegerField(blank=True, help_text='Diastolic blood pressure in mmHg', null=True)),
                ('blood_sugar_level', models.DecimalField(blank=True, decimal_places=2, help_text='Blood sugar level in mg/dL', max_digits=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
