# Generated by Django 5.0.4 on 2024-05-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_patientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='odf_file',
            field=models.FileField(blank=True, help_text='Upload ODF file', null=True, upload_to='files/'),
        ),
    ]
