# Generated by Django 5.0.4 on 2024-05-20 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0019_radiologistdoctor_radiologistdoctornotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('systolic_blood_pressure', models.IntegerField()),
                ('diastolic_blood_pressure', models.IntegerField()),
                ('blood_sugar_level', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('cholesterol_level', models.FloatField()),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
