# Generated by Django 5.0.4 on 2024-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0021_recomendation_delete_patientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologistdoctor',
            name='reccommendation',
            field=models.TextField(blank=True),
        ),
    ]
