# Generated by Django 5.0.4 on 2024-05-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0029_remove_appointment_doctor_appointment_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiologistdoctor',
            name='reccommendation',
        ),
        migrations.AddField(
            model_name='radiologistdoctor',
            name='recommendation',
            field=models.TextField(default='rest'),
            preserve_default=False,
        ),
    ]
