# Generated by Django 5.0.4 on 2024-05-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0030_remove_radiologistdoctor_reccommendation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorspecialistdata',
            old_name='reason',
            new_name='message',
        ),
    ]
