# Generated by Django 5.0.4 on 2024-06-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0031_rename_reason_doctorspecialistdata_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Specialist', 'Specialist'), ('Radiologist', 'Radiologist'), ('Receptionist', 'Receptionist')], max_length=15),
        ),
    ]
