# Generated by Django 5.0.4 on 2024-06-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0032_alter_customer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='doctorradiologist',
            name='reason',
        ),
    ]
