# Generated by Django 5.0.4 on 2024-06-04 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0035_doctorpatientmessagenotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MriScanImage',
        ),
    ]
