# Generated by Django 5.0.4 on 2024-06-04 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0042_delete_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_appointments_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
