# Generated by Django 5.0.4 on 2024-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0045_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentedImagePredictionTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('segmentation_result', models.ImageField(blank=True, null=True, upload_to='segmentation_results/')),
                ('classification_result', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
